name: Publish Backend

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'frontend/**'

env:
  AZURE_FUNCTIONAPP_NAME: aoe2cg-fa
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/.'
  DOTNET_VERSION: '3.1.201'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout master'
        uses: actions/checkout@master

      - name: Install dotnet SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'dotnet build'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Publish to Azure'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
