name: Build & Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/push-backend.yml'
      - 'backend/**'
      - 'templates/azuredeploy.json'

env:
  AZURE_FUNCTIONAPP_NAME: aoe2cg-fa
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/.'
  AZURE_RG_NAME: aoe2cg
  DOTNET_VERSION: '3.1.201'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout main'
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ env.AZURE_RG_NAME }} --template-file ./templates/azuredeploy.json --parameters '${{ secrets.ARM_TEMPLATE_PARAMETERS }}'

      - name: Install dotnet SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'dotnet build'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Publish to Azure'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
